// Copyright 2026 Jason Hane
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package crypto provides AES-256-GCM encryption for secrets stored in the database,
// and master key resolution from environment variables or filesystem.
package crypto

import (
	"encoding/base64"
	"fmt"
	"os"
	"runtime"
	"strings"
)

const (
	// EnvMasterKey is the environment variable for the base64-encoded master key.
	EnvMasterKey = "APP_MASTER_KEY"

	// KeySize is the required size of the master key in bytes (256 bits).
	KeySize = 32

	// linuxKeyPath is the default filesystem path for the master key on Linux.
	linuxKeyPath = "/etc/passport/key"

	// windowsKeyPath is the default filesystem path for the master key on Windows.
	windowsKeyPath = `C:\ProgramData\passport\key`
)

// LoadMasterKey resolves the master encryption key using the following priority:
//  1. APP_MASTER_KEY environment variable (base64-encoded 32 bytes)
//  2. Filesystem path: /etc/passport/key (Linux) or C:\ProgramData\passport\key (Windows)
func LoadMasterKey() ([]byte, error) {
	envErr := error(nil)
	if key, err := loadFromEnv(); err == nil {
		return key, nil
	} else if os.Getenv(EnvMasterKey) != "" {
		// Env var is set but has an error—report it instead of falling through
		envErr = err
	}

	if key, err := loadFromFile(keyFilePath()); err == nil {
		return key, nil
	}

	// If env var was set but had an error, report that error
	if envErr != nil {
		return nil, fmt.Errorf("failed to load %s: %w", EnvMasterKey, envErr)
	}

	return nil, fmt.Errorf(
		"master key not found: set %s environment variable (base64-encoded 32 bytes) or place raw key at %s",
		EnvMasterKey, keyFilePath(),
	)
}

func loadFromEnv() ([]byte, error) {
	val := os.Getenv(EnvMasterKey)
	if val == "" {
		return nil, fmt.Errorf("environment variable %s not set", EnvMasterKey)
	}

	key, err := decodeBase64(strings.TrimSpace(val))
	if err != nil {
		return nil, fmt.Errorf("decoding %s: %w", EnvMasterKey, err)
	}

	if len(key) != KeySize {
		return nil, fmt.Errorf("%s must be exactly %d bytes, got %d", EnvMasterKey, KeySize, len(key))
	}

	return key, nil
}

func loadFromFile(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading key file %s: %w", path, err)
	}

	// Try base64 first, fall back to raw bytes
	if decoded, err := decodeBase64(strings.TrimSpace(string(data))); err == nil && len(decoded) == KeySize {
		return decoded, nil
	}

	if len(data) == KeySize {
		return data, nil
	}

	return nil, fmt.Errorf("key file %s must contain exactly %d bytes (raw or base64-encoded), got %d", path, KeySize, len(data))
}

// decodeBase64 tries multiple base64 encodings: standard (with/without padding)
// and URL-safe (with/without padding). This handles keys generated by different tools.
func decodeBase64(s string) ([]byte, error) {
	encodings := []*base64.Encoding{
		base64.StdEncoding,
		base64.RawStdEncoding,
		base64.URLEncoding,
		base64.RawURLEncoding,
	}
	for _, enc := range encodings {
		if decoded, err := enc.DecodeString(s); err == nil {
			return decoded, nil
		}
	}
	return nil, fmt.Errorf("value is not valid base64 (tried standard and URL-safe encodings)")
}

func keyFilePath() string {
	if runtime.GOOS == "windows" {
		return windowsKeyPath
	}
	return linuxKeyPath
}
